<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:eg="http://www.badgers-in-foil.co.uk/projects/docbooc-css/tests/examples"
                xmlns="http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
		version="1.0">

  <xsl:output method="xml" indent="yes"/>
  <xsl:preserve-space elements="*"/>

  <xsl:template match="/*">
    <xsl:comment> Generated by localisation.xsl </xsl:comment>

    <xsl:processing-instruction name="xml-stylesheet">href="../driver.css" type="text/css"</xsl:processing-instruction>
    <article>
      <title>Localisation Examples</title>
      <section>
        <title>About</title>
	<para>This document shows off examples of all localisable content
	generated by the Docbook CSS stylesheet in all supported
	languages.  The actual content in each section is in English (they
	are all generated from the same source by an XSLT).  Important to
	note is the additional text added by the CSS.</para>
      </section>

      <section>
        <title>Locales</title>
        <xsl:for-each select="eg:list/*">
          <xsl:apply-templates mode="do-body" select="/*">
            <xsl:with-param name="lang" select="."/>
          </xsl:apply-templates>
        </xsl:for-each>
      </section>
    </article>
  </xsl:template>

  <xsl:template mode="do-body" match="eg:body">
    <section lang="{$lang/@code}" xml:lang="{$lang/@code}">
      <title><xsl:value-of select="$lang/text()"/></title>
      <xsl:copy-of select="./node()"/>
    </section>
  </xsl:template>
  <xsl:template mode="do-body" match="eg:list">
     <!-- ignore -->
  </xsl:template>
</xsl:stylesheet>
